<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Shipping.Domain\Shipping.Domain.csproj" />
    <ProjectReference Include="..\Shipping.Contracts\Shipping.Contracts.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\Security\Security.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\Infrastructure\Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\Messaging\Messaging.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
