using Customers.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Customers.Infrastructure.Persistence.Configurations;

public sealed class CustomerConfiguration : IEntityTypeConfiguration<Customer>
{
    public void Configure(EntityTypeBuilder<Customer> builder)
    {
        builder.ToTable("Customers");
        builder.HasKey(c => c.Id);

        // No ValueGenerated.Never override needed here beyond what AppDbContextBase already
        // applies to every entity (ADR-012) — Id is the same Guid as the owning ApplicationUser's,
        // assigned by the caller (Store.Web), never generated by the database.
        builder.Property(c => c.Email).HasMaxLength(256).IsRequired();
        builder.Property(c => c.FullName).HasMaxLength(200);
        builder.Property(c => c.Phone).HasMaxLength(30);

        builder.HasMany(c => c.Addresses)
            .WithOne()
            .HasForeignKey("CustomerId")
            .OnDelete(DeleteBehavior.Cascade);
    }
}

public sealed class CustomerAddressConfiguration : IEntityTypeConfiguration<CustomerAddress>
{
    public void Configure(EntityTypeBuilder<CustomerAddress> builder)
    {
        builder.ToTable("CustomerAddresses");
        builder.HasKey(a => a.Id);

        builder.Property(a => a.Label).HasMaxLength(100).IsRequired();
        builder.Property(a => a.FullName).HasMaxLength(200).IsRequired();
        builder.Property(a => a.Phone).HasMaxLength(30).IsRequired();
        builder.Property(a => a.Line1).HasMaxLength(300).IsRequired();
        builder.Property(a => a.Line2).HasMaxLength(300);
        builder.Property(a => a.City).HasMaxLength(150).IsRequired();
        builder.Property(a => a.State).HasMaxLength(150);
        builder.Property(a => a.PostalCode).HasMaxLength(20).IsRequired();
        builder.Property(a => a.Country).HasMaxLength(100).IsRequired();
    }
}
