<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Promotions.Domain\Promotions.Domain.csproj" />
    <ProjectReference Include="..\Promotions.Contracts\Promotions.Contracts.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\Security\Security.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\Infrastructure\Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
